export const furniturePhotos = [
  {
    category: "modern living",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/BartonSprings.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Highland.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Newton-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/VistaRidge-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Zilker-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/MIno-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/bluebonnet-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/jackson.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3032-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3035-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3036-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3040-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3041-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3044-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3052.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3054-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3055-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3061-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3062-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3068.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3069.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3070-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3076-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3080-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3083.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3091-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3094-scaled.jpg",
    ],
  },
  {
    category: "traditional living",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3134-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3132-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3131-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3130-1-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3129-1-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3128-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3127-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3098-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3063-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/3043-scaled.jpg",
    ],
  },
  {
    category: "bedroom",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Marlin.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/monarch-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Dulce-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/westlake-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Southwood-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Warner-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Lamar-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/2012-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/2015-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/2017-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/2022-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/2026-scaled.jpg",
    ],
  },
  {
    category: "kitchen dining",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/townlake.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Avalon.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Kinney-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4002.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/DiamondPoint-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Singleton-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4004.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4005.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4031.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4133.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4116.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4115.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/4134.jpg",
    ],
  },
  {
    category: "office",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/6011-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Raywood-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Frontier-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/RoyalCrest-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/6047-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/6049.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/6045-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/6042-scaled.jpg",
    ],
  },
  {
    category: "outdoor",
    src: [
      "https://virtualstagingsolutions.com/wp-content/uploads/2019/11/Summer-1.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7020-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7015-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7013-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7019-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7002-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7003-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7000-scaled.jpg",
      "https://virtualstagingsolutions.com/wp-content/uploads/2021/03/7027-scaled.jpg",
    ],
  },
];
